"""init tables

Revision ID: ea5a84cf22ed
Revises: 
Create Date: 2025-12-09 18:40:05.448363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5a84cf22ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adresy',
    sa.Column('id_adresu', sa.Integer(), nullable=False),
    sa.Column('ulica', sa.String(length=255), nullable=True),
    sa.Column('miasto', sa.String(length=100), nullable=True),
    sa.Column('kod_pocztowy', sa.String(length=20), nullable=True),
    sa.Column('wojewodztwo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_adresu')
    )
    op.create_table('Pracownicy',
    sa.Column('id_pracownika', sa.Integer(), nullable=False),
    sa.Column('imię', sa.String(length=255), nullable=False),
    sa.Column('nazwisko', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hasło', sa.String(length=255), nullable=False),
    sa.Column('nr_telefonu', sa.String(length=50), nullable=True),
    sa.Column('stanowisko', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_pracownika'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Typy_części',
    sa.Column('id_typu_części', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_typu_części')
    )
    op.create_table('Typy_urządzeń',
    sa.Column('id_typu', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_typu')
    )
    op.create_table('Części',
    sa.Column('id_części', sa.Integer(), nullable=False),
    sa.Column('id_typu_części', sa.Integer(), nullable=False),
    sa.Column('liczba_sztuk', sa.Integer(), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_typu_części'], ['Typy_części.id_typu_części'], ),
    sa.PrimaryKeyConstraint('id_części')
    )
    op.create_table('Klienci',
    sa.Column('id_klienta', sa.Integer(), nullable=False),
    sa.Column('id_adresu', sa.Integer(), nullable=True),
    sa.Column('imię', sa.String(length=100), nullable=False),
    sa.Column('nazwisko', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nr_telefonu', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_adresu'], ['Adresy.id_adresu'], ),
    sa.PrimaryKeyConstraint('id_klienta'),
    sa.UniqueConstraint('id_adresu')
    )
    op.create_table('Stanowiska',
    sa.Column('id_stanowiska', sa.Integer(), nullable=False),
    sa.Column('id_pracownika', sa.Integer(), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_pracownika'], ['Pracownicy.id_pracownika'], ),
    sa.PrimaryKeyConstraint('id_stanowiska')
    )
    op.create_table('Urządzenia',
    sa.Column('id_urzędzenia', sa.Integer(), nullable=False),
    sa.Column('id_klienta', sa.Integer(), nullable=False),
    sa.Column('typ_urządzenia', sa.Integer(), nullable=False),
    sa.Column('nr_seryjny', sa.String(length=100), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_klienta'], ['Klienci.id_klienta'], ),
    sa.ForeignKeyConstraint(['typ_urządzenia'], ['Typy_urządzeń.id_typu'], ),
    sa.PrimaryKeyConstraint('id_urzędzenia')
    )
    op.create_table('Zlecenia',
    sa.Column('id_zlecenia', sa.Integer(), nullable=False),
    sa.Column('id_klienta', sa.Integer(), nullable=False),
    sa.Column('id_urządzenia', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.Column('data_utworzenia', sa.Date(), nullable=True),
    sa.Column('termin_realizacji', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_klienta'], ['Klienci.id_klienta'], ),
    sa.ForeignKeyConstraint(['id_urządzenia'], ['Urządzenia.id_urzędzenia'], ),
    sa.PrimaryKeyConstraint('id_zlecenia')
    )
    op.create_table('Pracownicy_Zlecenia',
    sa.Column('id_pracownika', sa.Integer(), nullable=False),
    sa.Column('id_zlecenia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pracownika'], ['Pracownicy.id_pracownika'], ),
    sa.ForeignKeyConstraint(['id_zlecenia'], ['Zlecenia.id_zlecenia'], ),
    sa.PrimaryKeyConstraint('id_pracownika', 'id_zlecenia')
    )
    op.create_table('Używane_części',
    sa.Column('id_zlecenia', sa.Integer(), nullable=False),
    sa.Column('id_części', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_części'], ['Części.id_części'], ),
    sa.ForeignKeyConstraint(['id_zlecenia'], ['Zlecenia.id_zlecenia'], ),
    sa.PrimaryKeyConstraint('id_zlecenia', 'id_części')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Używane_części')
    op.drop_table('Pracownicy_Zlecenia')
    op.drop_table('Zlecenia')
    op.drop_table('Urządzenia')
    op.drop_table('Stanowiska')
    op.drop_table('Klienci')
    op.drop_table('Części')
    op.drop_table('Typy_urządzeń')
    op.drop_table('Typy_części')
    op.drop_table('Pracownicy')
    op.drop_table('Adresy')
    # ### end Alembic commands ###
